[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#3B82F6"
backgroundColor = "#0E131F"
secondaryBackgroundColor = "#1A2234"
textColor = "#F1F5F9"
font = "sans serif"

[browser]
gatherUsageStats = false
